import Head from 'next/head'
import Image from 'next/image'
import { useTranslation } from 'react-i18next';
import { Trans } from 'react-i18next';

import '../i18n/config';

import styles from '../styles/Home.module.css'

export default function Home() {

  const { t, i18n } = useTranslation();

  function changeLanguage(e) {
    i18n.changeLanguage(e.target.value);
  }

  const data = t('data', { returnObjects: true });

  return (
    <div className={styles.container}>
      <Head>
        <title>{t('title')}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.lang}>
          <button onClick={changeLanguage} value='en'>English</button>
          <button onClick={changeLanguage} value='esp'>Español</button>
        </div>
      <main className={styles.main}>
        
        <div className={styles.outlineborder}>
    
          <p className={styles.question}>
          <Trans i18nKey='question'></Trans>
          </p>

          <div className={styles.choicesContainer} key="containerChoice"> 
            {data && data.map((choice, index) => {
              if (index == 2) {
                return (
                  <>
                    <div className={styles.choice} key={'choice' + index}> 
                      <div className={styles.filledCircle} key={'choiceFill' + index}></div>
                      <div className={styles.pchoice} key={'choiceText' + index}>{choice}</div>
                    </div>
                  <br/>
                  </>
                );
              }
              else {
                return (
                  <>
                    <div className={styles.choice} key={'choicee' + index}> 
                      <div className={styles.circle} key={'choiceeFill' + index}></div>
                      <div className={styles.pchoice}key={'choiceeText' + index}>{choice}</div>
                    </div>
                  <br/>
                  </>
                  );
                }
            })}
          </div>
    

        </div>  
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
